### ISSUE TITLE
Make default search result period any

### ISSUE THREAD

**Issue by SunburntRock89** [gatecrasher777/ytcog#17]
const search = new ytcog.Search(session, {
		"take my breath the weeknd",
		order: "views",
}

I just spent over an hour trying to figure out why this search would be returning such weird results, only to find out that this library returns the newest uploads instead of the usual search behaviour of defaulting to all-time results. I'd like to suggest that this is changed to emulate the search bar on YouTube itself.

**Comment by gatecrasher777** [comment]
Thanks for using the library, and I'm sorry you had to struggle.

I also hope you found the [search options](https://github.com/gatecrasher777/ytcog/wiki/Search)

Yes, the default search settings are:

```javascript
		{
			query: 'video',
			order: 'relevance', 
			period: 'day',
			items: 'videos',  
			duration: 'any',  
			features: '',
			quantity: 100
		}
```
So for your request: 

```javascript
		{
			query: 'take my breath the weeknd',
			order: 'views',
			period: 'any',
			quantity: 20
		}
```
would search all results and return the top 20 results ordered by decreasing number of views.

I can make the default period 'any' to match YouTube.  Its not really a problem. I had it set to 'day' because I use this library in a news project that only searches for videos less than 24 hours old.

**Comment by SunburntRock89** [comment]
Ah, that makes sense, it's just a little confusing for a newbie to the library is all, thanks for being so helpful!
