### ISSUE TITLE
Is it possible to find shorts and videos?

### ISSUE THREAD

**Issue by edergames29** [gatecrasher777/ytcog#55]
```
searchOptions = {
                    query: "https://www.youtube.com/shorts/IXCkBMFChvU?feature=share",
                    items: "any",
                    quantity: 1
                }
```
I'm using these search parameters but it doesn't find the selected **shorts**

This is a piece of output.
```
  quantity: 0,
  latest: 0,
  results: [],
  videos: [],
  channels: [],
  playlists: [],
  estimated: 0,
  page: 0,
  more: '',
  updated: 1686948331353
```

**Comment by gatecrasher777** [comment]
I'm not sure what kind of result you expect.  You are searching for a link to a specific shorts video, rather than results for a specific search term (like "formula one" or topic "football"). So estimated: 0 means that nothing matches your search term which is essentially a link to which YouTube cannot interpret and find a match.

Search fetch results will include shorts and videos that match the search term.  Shorts are included in the videos array.

Channel fetch results (a specific channel with items: "search" ) will also return shorts and videos. However for items: "videos" and items: "shorts" you can get (longer) videos or shorts respectively.

**Comment by edergames29** [comment]
> Não tenho certeza de que tipo de resultado você espera. Você está procurando um link para um vídeo curto específico, em vez de resultados para um termo de pesquisa específico (como "fórmula um" ou tópico "futebol"). Assim estimado: 0 significa que nada corresponde ao seu termo de pesquisa, que é essencialmente um link para o qual o YouTube não consegue interpretar e encontrar uma correspondência.
> 
> Os resultados da busca incluirão curtas e vídeos que correspondem ao termo de pesquisa. Shorts são incluídos na matriz de vídeos.
> 
> Os resultados da busca do canal (um canal específico com itens: "search" ) também retornarão shorts e vídeos. No entanto, para itens: "vídeos" e itens: "shorts" você pode obter vídeos (mais longos) ou curtas, respectivamente.

Apparently removing everything and leaving only the id, the result appears, now just find a way to handle the link and get just the id.
![Screenshot_20230622_030412_YouTube](https://github.com/gatecrasher777/ytcog/assets/52362327/6db74c76-92c0-4ca5-90a6-6845dffd7e9b)
